In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
nd=pd.read_excel("/content/cricket data.xlsx")
nd

,Match_ID,Innings,Batting_Team,Bowling_Team,Venue,Match_Format,Batsman_Name,Bowler_Name,Runs_Scored,Balls_Faced,...,Total_Boundaries,Strike_Rate_Calc,Wickets_Taken,Overs_Numeric,Economy_Rate,Dismissal_Type,Player_Role,Match_Date_Clean,Match_Month,Match_Year
0,78001,2,India,West Indies,Melbourne,ODI,Williamson,Afridi,160,16,...,84,1000.00,3,5.912402,15.90,Caught,Bowler,2020-01-01,2020-01,2020.0
1,65307,1,England,New Zealand,Auckland,ODI,Kohli,Southee,32,33,...,130,96.97,0,5.912402,9.13,Caught,Batsman,NaN,NaN,NaN
2,26732,2,Australia,West Indies,Auckland,ODI,Kohli,Joseph,43,109,...,94,39.45,3,5.912402,6.09,Run Out,Batsman,NaN,NaN,NaN
3,18742,1,Afghanistan,New Zealand,Mumbai,T20,Williamson,Woakes,167,74,...,80,225.68,0,NaN,NaN,LBW,Batsman,NaN,NaN,NaN
4,10028,1,Australia,South Africa,Kolkata,ODI,Smith,Malinga,129,136,...,84,94.85,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,28229,2,Pakistan,West Indies,Mumbai,Test,Russell,Malinga,165,70,...,58,235.71,4,5.912402,13.53,Bowled,All-Rounder,NaN,NaN,NaN
4994,13475,1,Australia,India,Chennai,T20,Faf,Southee,39,38,...,104,102.63,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN
4995,44948,1,New Zealand,Australia,London,Test,Russell,Woakes,72,6,...,120,1200.00,0,NaN,NaN,Run Out,Bowler,NaN,NaN,NaN
4996,66636,1,West Indies,England,Mumbai,Test,Kohli,Joseph,176,72,...,104,244.44,4,5.912402,14.38,Caught,Batsman,2021-05-10,2021-05,2021.0
4997,81582,1,Bangladesh,Pakistan,Auckland,T20,Smith,Bumrah,156,113,...,116,138.05,-1,NaN,NaN,Not Out,NaN,2020-01-01,2020-01,2020.0

In [3]:
print("Shape:",nd.shape)
print("\nInfo:")
print(nd.info())
print("\nStatistics:")
print(nd.describe)

Shape: (4998, 22)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4998 entries, 0 to 4997
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Match_ID          4998 non-null   int64
 1   Innings           4998 non-null   int64
 2   Batting_Team      4998 non-null   object
 3   Bowling_Team      4998 non-null   object
 4   Venue             4467 non-null   object
 5   Match_Format      4998 non-null   object
 6   Batsman_Name      4998 non-null   object
 7   Bowler_Name       4998 non-null   object
 8   Runs_Scored       4998 non-null   int64
 9   Balls_Faced       4998 non-null   int64
 10  Fours             4998 non-null   int64
 11  Sixes             4998 non-null   int64
 12  Total_Boundaries  4998 non-null   int64
 13  Strike_Rate_Calc  4967 non-null   float64
 14  Wickets_Taken     4998 non-null   int64
 15  Overs_Numeric     1699 non-null   float64
 16  Economy_Rate      1699 non-null   float64
 17  Dismissal_Type    4998 non-null   object
 18  Player_Role       3790 non-null   object
 19  Match_Date_Clean  2491 non-null   object
 20  Match_Month       2491 non-null   object
 21  Match_Year        2491 non-null   float64
dtypes: float64(4), int64(8), object(10)
memory usage: 859.2+ KB
None

Statistics:
<bound method NDFrame.describe of       Match_ID  Innings Batting_Team  Bowling_Team      Venue Match_Format  \
0        78001        2        India   West Indies  Melbourne          ODI
1        65307        1      England   New Zealand   Auckland          ODI
2        26732        2    Australia   West Indies   Auckland          ODI
3        18742        1  Afghanistan   New Zealand     Mumbai          T20
4        10028        1    Australia  South Africa    Kolkata          ODI
...        ...      ...          ...           ...        ...          ...
4993     28229        2     Pakistan   West Indies     Mumbai         Test
4994     13475        1    Australia         India    Chennai          T20
4995     44948        1  New Zealand     Australia     London         Test
4996     66636        1  West Indies       England     Mumbai         Test
4997     81582        1   Bangladesh      Pakistan   Auckland          T20

     Batsman_Name Bowler_Name  Runs_Scored  Balls_Faced  ...  \
0      Williamson      Afridi          160           16  ...
1           Kohli     Southee           32           33  ...
2           Kohli      Joseph           43          109  ...
3      Williamson      Woakes          167           74  ...
4           Smith     Malinga          129          136  ...
...           ...         ...          ...          ...  ...
4993      Russell     Malinga          165           70  ...
4994          Faf     Southee           39           38  ...
4995      Russell      Woakes           72            6  ...
4996        Kohli      Joseph          176           72  ...
4997        Smith      Bumrah          156          113  ...

      Total_Boundaries  Strike_Rate_Calc  Wickets_Taken  Overs_Numeric  \
0                   84           1000.00              3       5.912402
1                  130             96.97              0       5.912402
2                   94             39.45              3       5.912402
3                   80            225.68              0            NaN
4                   84             94.85              1            NaN
...                ...               ...            ...            ...
4993                58            235.71              4       5.912402
4994               104            102.63              1            NaN
4995               120           1200.00              0            NaN
4996               104            244.44              4       5.912402
4997               116            138.05             -1            NaN

      Economy_Rate  Dismissal_Type  Player_Role Match_Date_Clean Match_Month  \
0            15.90          Caught       Bowler       2020-01-01     2020-01
1             9.13          Caught      Batsman              NaN         NaN
2             6.09         Run Out      Batsman              NaN         NaN
3              NaN             LBW      Batsman              NaN         NaN
4              NaN             LBW  All-Rounder              NaN         NaN
...            ...             ...          ...              ...         ...
4993         13.53          Bowled  All-Rounder              NaN         NaN
4994           NaN             LBW  All-Rounder              NaN         NaN
4995           NaN         Run Out       Bowler              NaN         NaN
4996         14.38          Caught      Batsman       2021-05-10     2021-05
4997           NaN         Not Out          NaN       2020-01-01     2020-01

     Match_Year
0        2020.0
1           NaN
2           NaN
3           NaN
4           NaN
...         ...
4993        NaN
4994        NaN
4995        NaN
4996     2021.0
4997     2020.0

[4998 rows x 22 columns]>

In [4]:
print(nd.isnull().sum())
invalid_value=["NA","Unkown","","---","-"]
print(nd.isin(invalid_value).sum())

Match_ID               0
Innings                0
Batting_Team           0
Bowling_Team           0
Venue                531
Match_Format           0
Batsman_Name           0
Bowler_Name            0
Runs_Scored            0
Balls_Faced            0
Fours                  0
Sixes                  0
Total_Boundaries       0
Strike_Rate_Calc      31
Wickets_Taken          0
Overs_Numeric       3299
Economy_Rate        3299
Dismissal_Type         0
Player_Role         1208
Match_Date_Clean    2507
Match_Month         2507
Match_Year          2507
dtype: int64
Match_ID            0
Innings             0
Batting_Team        0
Bowling_Team        0
Venue               0
Match_Format        0
Batsman_Name        0
Bowler_Name         0
Runs_Scored         0
Balls_Faced         0
Fours               0
Sixes               0
Total_Boundaries    0
Strike_Rate_Calc    0
Wickets_Taken       0
Overs_Numeric       0
Economy_Rate        0
Dismissal_Type      0
Player_Role         0
Match_Date_Clean    0
Match_Month         0
Match_Year          0
dtype: int64

In [7]:
import numpy as np
nd.replace(["NA", "Unknown", "", "---", "-"], np.nan, inplace=True)
nd

,Match_ID,Innings,Batting_Team,Bowling_Team,Venue,Match_Format,Batsman_Name,Bowler_Name,Runs_Scored,Balls_Faced,...,Total_Boundaries,Strike_Rate_Calc,Wickets_Taken,Overs_Numeric,Economy_Rate,Dismissal_Type,Player_Role,Match_Date_Clean,Match_Month,Match_Year
0,78001,2,India,West Indies,Melbourne,ODI,Williamson,Afridi,160,16,...,84,1000.00,3,5.912402,15.90,Caught,Bowler,2020-01-01,2020-01,2020.0
1,65307,1,England,New Zealand,Auckland,ODI,Kohli,Southee,32,33,...,130,96.97,0,5.912402,9.13,Caught,Batsman,NaN,NaN,NaN
2,26732,2,Australia,West Indies,Auckland,ODI,Kohli,Joseph,43,109,...,94,39.45,3,5.912402,6.09,Run Out,Batsman,NaN,NaN,NaN
3,18742,1,Afghanistan,New Zealand,Mumbai,T20,Williamson,Woakes,167,74,...,80,225.68,0,NaN,NaN,LBW,Batsman,NaN,NaN,NaN
4,10028,1,Australia,South Africa,Kolkata,ODI,Smith,Malinga,129,136,...,84,94.85,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,28229,2,Pakistan,West Indies,Mumbai,Test,Russell,Malinga,165,70,...,58,235.71,4,5.912402,13.53,Bowled,All-Rounder,NaN,NaN,NaN
4994,13475,1,Australia,India,Chennai,T20,Faf,Southee,39,38,...,104,102.63,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN
4995,44948,1,New Zealand,Australia,London,Test,Russell,Woakes,72,6,...,120,1200.00,0,NaN,NaN,Run Out,Bowler,NaN,NaN,NaN
4996,66636,1,West Indies,England,Mumbai,Test,Kohli,Joseph,176,72,...,104,244.44,4,5.912402,14.38,Caught,Batsman,2021-05-10,2021-05,2021.0
4997,81582,1,Bangladesh,Pakistan,Auckland,T20,Smith,Bumrah,156,113,...,116,138.05,-1,NaN,NaN,Not Out,NaN,2020-01-01,2020-01,2020.0

In [15]:
nd["Runs_Scored"] = pd.to_numeric(nd["Runs_Scored"], errors="coerce")

nd["Balls_Faced"] = pd.to_numeric(nd["Balls_Faced"], errors="coerce")

nd["Strike_Rate_Calc"] = pd.to_numeric(nd["Strike_Rate_Calc"], errors="coerce")

nd["Overs_Numeric"] = pd.to_numeric(nd["Overs_Numeric"], errors="coerce")

nd["Runs_Scored"] = pd.to_numeric(nd["Runs_Scored"], errors="coerce")

nd["Wickets_Taken"] = pd.to_numeric(nd["Wickets_Taken"], errors="coerce")
nd

,Match_ID,Innings,Batting_Team,Bowling_Team,Venue,Match_Format,Batsman_Name,Bowler_Name,Runs_Scored,Balls_Faced,...,Total_Boundaries,Strike_Rate_Calc,Wickets_Taken,Overs_Numeric,Economy_Rate,Dismissal_Type,Player_Role,Match_Date_Clean,Match_Month,Match_Year
0,78001,2,India,West Indies,Melbourne,ODI,Williamson,Afridi,160,16,...,84,1000.00,3,5.912402,15.90,Caught,Bowler,2020-01-01,2020-01,2020.0
1,65307,1,England,New Zealand,Auckland,ODI,Kohli,Southee,32,33,...,130,96.97,0,5.912402,9.13,Caught,Batsman,NaN,NaN,NaN
2,26732,2,Australia,West Indies,Auckland,ODI,Kohli,Joseph,43,109,...,94,39.45,3,5.912402,6.09,Run Out,Batsman,NaN,NaN,NaN
3,18742,1,Afghanistan,New Zealand,Mumbai,T20,Williamson,Woakes,167,74,...,80,225.68,0,NaN,NaN,LBW,Batsman,NaN,NaN,NaN
4,10028,1,Australia,South Africa,Kolkata,ODI,Smith,Malinga,129,136,...,84,94.85,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,28229,2,Pakistan,West Indies,Mumbai,Test,Russell,Malinga,165,70,...,58,235.71,4,5.912402,13.53,Bowled,All-Rounder,NaN,NaN,NaN
4994,13475,1,Australia,India,Chennai,T20,Faf,Southee,39,38,...,104,102.63,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN
4995,44948,1,New Zealand,Australia,London,Test,Russell,Woakes,72,6,...,120,1200.00,0,NaN,NaN,Run Out,Bowler,NaN,NaN,NaN
4996,66636,1,West Indies,England,Mumbai,Test,Kohli,Joseph,176,72,...,104,244.44,4,5.912402,14.38,Caught,Batsman,2021-05-10,2021-05,2021.0
4997,81582,1,Bangladesh,Pakistan,Auckland,T20,Smith,Bumrah,156,113,...,116,138.05,-1,NaN,NaN,Not Out,NaN,2020-01-01,2020-01,2020.0

In [16]:
nd["Batting_StrikeRate"] = (nd["Runs_Scored"] / nd["Balls_Faced"]) * 100
nd

,Match_ID,Innings,Batting_Team,Bowling_Team,Venue,Match_Format,Batsman_Name,Bowler_Name,Runs_Scored,Balls_Faced,...,Strike_Rate_Calc,Wickets_Taken,Overs_Numeric,Economy_Rate,Dismissal_Type,Player_Role,Match_Date_Clean,Match_Month,Match_Year,Batting_StrikeRate
0,78001,2,India,West Indies,Melbourne,ODI,Williamson,Afridi,160,16,...,1000.00,3,5.912402,15.90,Caught,Bowler,2020-01-01,2020-01,2020.0,1000.000000
1,65307,1,England,New Zealand,Auckland,ODI,Kohli,Southee,32,33,...,96.97,0,5.912402,9.13,Caught,Batsman,NaN,NaN,NaN,96.969697
2,26732,2,Australia,West Indies,Auckland,ODI,Kohli,Joseph,43,109,...,39.45,3,5.912402,6.09,Run Out,Batsman,NaN,NaN,NaN,39.449541
3,18742,1,Afghanistan,New Zealand,Mumbai,T20,Williamson,Woakes,167,74,...,225.68,0,NaN,NaN,LBW,Batsman,NaN,NaN,NaN,225.675676
4,10028,1,Australia,South Africa,Kolkata,ODI,Smith,Malinga,129,136,...,94.85,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN,94.852941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,28229,2,Pakistan,West Indies,Mumbai,Test,Russell,Malinga,165,70,...,235.71,4,5.912402,13.53,Bowled,All-Rounder,NaN,NaN,NaN,235.714286
4994,13475,1,Australia,India,Chennai,T20,Faf,Southee,39,38,...,102.63,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN,102.631579
4995,44948,1,New Zealand,Australia,London,Test,Russell,Woakes,72,6,...,1200.00,0,NaN,NaN,Run Out,Bowler,NaN,NaN,NaN,1200.000000
4996,66636,1,West Indies,England,Mumbai,Test,Kohli,Joseph,176,72,...,244.44,4,5.912402,14.38,Caught,Batsman,2021-05-10,2021-05,2021.0,244.444444
4997,81582,1,Bangladesh,Pakistan,Auckland,T20,Smith,Bumrah,156,113,...,138.05,-1,NaN,NaN,Not Out,NaN,2020-01-01,2020-01,2020.0,138.053097

In [17]:
nd["Bowling_Economy"] = nd["Runs_Scored"] / nd["Overs_Numeric"]
nd

,Match_ID,Innings,Batting_Team,Bowling_Team,Venue,Match_Format,Batsman_Name,Bowler_Name,Runs_Scored,Balls_Faced,...,Wickets_Taken,Overs_Numeric,Economy_Rate,Dismissal_Type,Player_Role,Match_Date_Clean,Match_Month,Match_Year,Batting_StrikeRate,Bowling_Economy
0,78001,2,India,West Indies,Melbourne,ODI,Williamson,Afridi,160,16,...,3,5.912402,15.90,Caught,Bowler,2020-01-01,2020-01,2020.0,1000.000000,27.061760
1,65307,1,England,New Zealand,Auckland,ODI,Kohli,Southee,32,33,...,0,5.912402,9.13,Caught,Batsman,NaN,NaN,NaN,96.969697,5.412352
2,26732,2,Australia,West Indies,Auckland,ODI,Kohli,Joseph,43,109,...,3,5.912402,6.09,Run Out,Batsman,NaN,NaN,NaN,39.449541,7.272848
3,18742,1,Afghanistan,New Zealand,Mumbai,T20,Williamson,Woakes,167,74,...,0,NaN,NaN,LBW,Batsman,NaN,NaN,NaN,225.675676,NaN
4,10028,1,Australia,South Africa,Kolkata,ODI,Smith,Malinga,129,136,...,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN,94.852941,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,28229,2,Pakistan,West Indies,Mumbai,Test,Russell,Malinga,165,70,...,4,5.912402,13.53,Bowled,All-Rounder,NaN,NaN,NaN,235.714286,27.907440
4994,13475,1,Australia,India,Chennai,T20,Faf,Southee,39,38,...,1,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN,102.631579,NaN
4995,44948,1,New Zealand,Australia,London,Test,Russell,Woakes,72,6,...,0,NaN,NaN,Run Out,Bowler,NaN,NaN,NaN,1200.000000,NaN
4996,66636,1,West Indies,England,Mumbai,Test,Kohli,Joseph,176,72,...,4,5.912402,14.38,Caught,Batsman,2021-05-10,2021-05,2021.0,244.444444,29.767936
4997,81582,1,Bangladesh,Pakistan,Auckland,T20,Smith,Bumrah,156,113,...,-1,NaN,NaN,Not Out,NaN,2020-01-01,2020-01,2020.0,138.053097,NaN

In [18]:
venue_summary = nd.groupby("Venue").agg({
    "Runs_Scored": "mean",
    "Batting_StrikeRate": "mean"
}).reset_index()

print(venue_summary)

          Venue  Runs_Scored  Batting_StrikeRate
0      Auckland    81.604790          294.875062
1       Chennai    80.522267                 inf
2         Delhi    83.814672                 NaN
3  Johannesburg    84.268559                 NaN
4       Kolkata    86.604462                 inf
5        London    79.458248                 inf
6     Melbourne    84.508097                 inf
7        Mumbai    88.036961                 inf
8        Sydney    80.644068                 inf

In [20]:
batsman_summary = nd.groupby("Batsman_Name").agg({
    "Runs_Scored": "sum",
    "Wickets_Taken": "mean"
}).reset_index()

print(batsman_summary)

  Batsman_Name  Runs_Scored  Wickets_Taken
0        Babar        41094       2.426854
1          Faf        39132       2.428870
2        Kohli        44185       2.491773
3         Nabi        41523       2.305720
4        Rohit        41348       2.548654
5         Root        40261       2.643006
6      Russell        39470       2.553684
7        Smith        41833       2.465726
8       Warner        44234       2.393881
9   Williamson        43682       2.518591

In [23]:
import pandas as pd

# 1. Aggregate runs scored by Batting_Team for each Match_ID
#    This sums up all individual batsman runs for a given team in a given match.
team_total_runs = nd.groupby(['Match_ID', 'Batting_Team'])['Runs_Scored'].sum().reset_index()

# 2. Determine match outcomes for each match
match_outcomes = {}
for match_id in team_total_runs['Match_ID'].unique():
    match_teams_data = team_total_runs[team_total_runs['Match_ID'] == match_id]

    if len(match_teams_data) == 2: # Expecting two teams per match for a clear win/loss
        team1_name = match_teams_data.iloc[0]['Batting_Team']
        team1_score = match_teams_data.iloc[0]['Runs_Scored']
        team2_name = match_teams_data.iloc[1]['Batting_Team']
        team2_score = match_teams_data.iloc[1]['Runs_Scored']

        if team1_score > team2_score:
            match_outcomes[match_id] = {team1_name: 'Win', team2_name: 'Loss'}
        elif team2_score > team1_score:
            match_outcomes[match_id] = {team1_name: 'Loss', team2_name: 'Win'}
        else: # Tie or Draw
            match_outcomes[match_id] = {team1_name: 'Tie/Draw', team2_name: 'Tie/Draw'}
    elif len(match_teams_data) < 2:
        # Handle cases where only one team's data is available (e.g., incomplete match, data error)
        for _, row in match_teams_data.iterrows():
            match_outcomes.setdefault(match_id, {})[row['Batting_Team']] = 'Incomplete'
    else:
        # Handle cases where more than two teams appear for a Match_ID (e.g., data error or specific formats like triangular series where one match_id might involve more than 2 teams)
        # For simplicity, these will be marked as 'Ambiguous' or 'Unknown' as direct win/loss comparison is difficult.
        for _, row in match_teams_data.iterrows():
            match_outcomes.setdefault(match_id, {})[row['Batting_Team']] = 'Ambiguous'

# 3. Update the 'Match_Result' column in the original DataFrame `nd`
def assign_match_result(row):
    match_id = row['Match_ID']
    batting_team = row['Batting_Team']
    return match_outcomes.get(match_id, {}).get(batting_team, 'Unknown')

nd['Match_Result'] = nd.apply(assign_match_result, axis=1)
display(nd.head())

,Match_ID,Innings,Batting_Team,Bowling_Team,Venue,Match_Format,Batsman_Name,Bowler_Name,Runs_Scored,Balls_Faced,...,Overs_Numeric,Economy_Rate,Dismissal_Type,Player_Role,Match_Date_Clean,Match_Month,Match_Year,Batting_StrikeRate,Bowling_Economy,Match_Result
0,78001,2,India,West Indies,Melbourne,ODI,Williamson,Afridi,160,16,...,5.912402,15.90,Caught,Bowler,2020-01-01,2020-01,2020.0,1000.000000,27.061760,Incomplete
1,65307,1,England,New Zealand,Auckland,ODI,Kohli,Southee,32,33,...,5.912402,9.13,Caught,Batsman,NaN,NaN,NaN,96.969697,5.412352,Loss
2,26732,2,Australia,West Indies,Auckland,ODI,Kohli,Joseph,43,109,...,5.912402,6.09,Run Out,Batsman,NaN,NaN,NaN,39.449541,7.272848,Incomplete
3,18742,1,Afghanistan,New Zealand,Mumbai,T20,Williamson,Woakes,167,74,...,NaN,NaN,LBW,Batsman,NaN,NaN,NaN,225.675676,NaN,Incomplete
4,10028,1,Australia,South Africa,Kolkata,ODI,Smith,Malinga,129,136,...,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN,94.852941,NaN,Incomplete

In [25]:
top_performances = nd[nd["Match_Result"] == "Win"] \
                    .sort_values(by="Runs_Scored", ascending=False) \
                    .head(10)

print(top_performances)
nd

      Match_ID  Innings  Batting_Team  Bowling_Team         Venue  \
2847     62186        2     Australia    Bangladesh       Kolkata
3555     51586        1       England   New Zealand        London
3426     83916        2  South Africa       England        Sydney
1904     77419        1       England  South Africa       Chennai
1538     33785        1   Afghanistan    Bangladesh        London
2769     54911        2     Sri Lanka         India        Mumbai
368      80310        2         India     Sri Lanka  Johannesburg
263      54176        1         India      Pakistan      Auckland
2323     98939        1   New Zealand       England     Melbourne
1224     67488        1     Sri Lanka  South Africa       Kolkata

     Match_Format Batsman_Name Bowler_Name  Runs_Scored  Balls_Faced  ...  \
2847          ODI         Root      Bumrah          179          145  ...
3555          ODI      Russell      Rashid          179           92  ...
3426          ODI         Nabi     Southee          178            1  ...
1904         Test         Nabi     Malinga          176           41  ...
1538          ODI         Root       Shami          176           78  ...
2769          ODI      Russell      Rashid          176           62  ...
368           ODI         Nabi      Woakes          175           70  ...
263          Test          Faf       Shami          174           53  ...
2323          ODI        Kohli       Starc          174          140  ...
1224          ODI      Russell      Rabada          174          134  ...

      Overs_Numeric  Economy_Rate  Dismissal_Type  Player_Role  \
2847            NaN           NaN         Stumped      Batsman
3555            NaN           NaN             LBW  All-Rounder
3426            NaN           NaN          Caught          NaN
1904       5.912402         15.05          Caught       Bowler
1538       5.912402         16.58             LBW          NaN
2769       5.912402          9.98          Caught       Bowler
368        5.912402          8.46         Run Out          NaN
263        5.912402         14.04             LBW  All-Rounder
2323            NaN           NaN             LBW          NaN
1224            NaN           NaN             LBW       Bowler

      Match_Date_Clean  Match_Month  Match_Year Batting_StrikeRate  \
2847               NaN          NaN         NaN         123.448276
3555        2020-01-01      2020-01      2020.0         194.565217
3426               NaN          NaN         NaN       17800.000000
1904        2020-01-01      2020-01      2020.0         429.268293
1538               NaN          NaN         NaN         225.641026
2769        2021-05-10      2021-05      2021.0         283.870968
368                NaN          NaN         NaN         250.000000
263         2021-05-10      2021-05      2021.0         328.301887
2323               NaN          NaN         NaN         124.285714
1224        2021-05-10      2021-05      2021.0         129.850746

     Bowling_Economy Match_Result
2847             NaN          Win
3555             NaN          Win
3426             NaN          Win
1904       29.767936          Win
1538       29.767936          Win
2769       29.767936          Win
368        29.598800          Win
263        29.429664          Win
2323             NaN          Win
1224             NaN          Win

[10 rows x 25 columns]

,Match_ID,Innings,Batting_Team,Bowling_Team,Venue,Match_Format,Batsman_Name,Bowler_Name,Runs_Scored,Balls_Faced,...,Overs_Numeric,Economy_Rate,Dismissal_Type,Player_Role,Match_Date_Clean,Match_Month,Match_Year,Batting_StrikeRate,Bowling_Economy,Match_Result
0,78001,2,India,West Indies,Melbourne,ODI,Williamson,Afridi,160,16,...,5.912402,15.90,Caught,Bowler,2020-01-01,2020-01,2020.0,1000.000000,27.061760,Incomplete
1,65307,1,England,New Zealand,Auckland,ODI,Kohli,Southee,32,33,...,5.912402,9.13,Caught,Batsman,NaN,NaN,NaN,96.969697,5.412352,Loss
2,26732,2,Australia,West Indies,Auckland,ODI,Kohli,Joseph,43,109,...,5.912402,6.09,Run Out,Batsman,NaN,NaN,NaN,39.449541,7.272848,Incomplete
3,18742,1,Afghanistan,New Zealand,Mumbai,T20,Williamson,Woakes,167,74,...,NaN,NaN,LBW,Batsman,NaN,NaN,NaN,225.675676,NaN,Incomplete
4,10028,1,Australia,South Africa,Kolkata,ODI,Smith,Malinga,129,136,...,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN,94.852941,NaN,Incomplete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,28229,2,Pakistan,West Indies,Mumbai,Test,Russell,Malinga,165,70,...,5.912402,13.53,Bowled,All-Rounder,NaN,NaN,NaN,235.714286,27.907440,Incomplete
4994,13475,1,Australia,India,Chennai,T20,Faf,Southee,39,38,...,NaN,NaN,LBW,All-Rounder,NaN,NaN,NaN,102.631579,NaN,Incomplete
4995,44948,1,New Zealand,Australia,London,Test,Russell,Woakes,72,6,...,NaN,NaN,Run Out,Bowler,NaN,NaN,NaN,1200.000000,NaN,Incomplete
4996,66636,1,West Indies,England,Mumbai,Test,Kohli,Joseph,176,72,...,5.912402,14.38,Caught,Batsman,2021-05-10,2021-05,2021.0,244.444444,29.767936,Incomplete
4997,81582,1,Bangladesh,Pakistan,Auckland,T20,Smith,Bumrah,156,113,...,NaN,NaN,Not Out,NaN,2020-01-01,2020-01,2020.0,138.053097,NaN,Incomplete

In [27]:
format_summary = nd.groupby("Match_Format").agg({
    "Runs_Scored": "mean",
    "Batting_StrikeRate": "mean",
    "Wickets_Taken": "mean",
    "Bowling_Economy": "mean"
}).reset_index()

print(format_summary)

  Match_Format  Runs_Scored  Batting_StrikeRate  Wickets_Taken  \
0          ODI    83.335685                 inf       2.442681
1          T20    83.125989                 NaN       2.429702
2         Test    83.695284                 NaN       2.556832

   Bowling_Economy
0        13.484949
1        14.132084
2        14.453879

In [28]:
nd.to_csv("cleaned_cricket_data.csv", index=False)